# Generated by Django 5.2.11 on 2026-02-23 01:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_address'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('extra_ingredients', models.ManyToManyField(blank=True, related_name='extra_cart_items', to='products.ingredient')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.pizza')),
                ('removed_ingredients', models.ManyToManyField(blank=True, related_name='removed_cart_items', to='products.ingredient')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.pizzasize')),
            ],
            options={
                'db_table': 'orders_cart_item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('order_type', models.CharField(choices=[('delivery', 'Consegna'), ('pickup', 'Ritiro'), ('dine_in', 'In sede')], default='delivery', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('confirmed', 'Confermato'), ('preparing', 'In Preparazione'), ('ready', 'Pronto'), ('out_for_delivery', 'In Consegna'), ('delivered', 'Consegnato'), ('cancelled', 'Annullato'), ('refunded', 'Rimborsato')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=17)),
                ('status', models.CharField(choices=[('assigned', 'Assegnato'), ('in_transit', 'In transito'), ('delivered', 'Consegnato'), ('failed', 'Fallito')], max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('customer_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='orders.order')),
            ],
            options={
                'db_table': 'orders_delivery_info',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('extra_ingredients_snapshot', models.JSONField(default=list)),
                ('removed_ingredients_snapshot', models.JSONField(default=list)),
                ('preparation_status', models.CharField(choices=[('pending', 'In attesa'), ('preparing', 'In preparazione'), ('ready', 'Pronto')], default='pending', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.pizza')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.pizzasize')),
            ],
            options={
                'db_table': 'orders_order_item',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('card', 'Carta'), ('paypal', 'PayPal'), ('cash', 'Contanti')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('processing', 'In elaborazione'), ('completed', 'Completato'), ('failed', 'Fallito'), ('refunded', 'Rimborsato')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'orders_payment',
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_active_cart_per_user'),
        ),
    ]
