# Generated by Django 5.2.11 on 2026-06-04 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("register", "Register"),
                            ("payment", "Payment"),
                            ("status_change", "Status Change"),
                            ("permission_change", "Permission Change"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="audit_log_user_id_4dac76_idx"),
                    models.Index(
                        fields=["action_type"], name="audit_log_action__ff81b5_idx"
                    ),
                    models.Index(
                        fields=["model_name"], name="audit_log_model_n_d0c22c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_log_created_5a7975_idx"
                    ),
                ],
            },
        ),
    ]
