# Generated by Django 5.2.11 on 2026-02-23 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'products_allergen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('name', models.CharField(max_length=20, unique=True)),
                ('diameter_cm', models.PositiveIntegerField()),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products_pizza_size',
                'ordering': ['diameter_cm'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category')),
            ],
            options={
                'db_table': 'products_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_extra', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('allergens', models.ManyToManyField(blank=True, to='products.allergen')),
            ],
            options={
                'db_table': 'products_ingredient',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pizzas/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pizzas', to='products.category')),
            ],
            options={
                'db_table': 'products_pizza',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PizzaIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e ora di creazione del record.')),
                ('update_at', models.DateTimeField(auto_now=True, help_text="Data e l'ora di l'ultima modifica.")),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_removable', models.BooleanField(default=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ingredient')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pizza')),
            ],
            options={
                'db_table': 'products_pizza_ingredient',
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(through='products.PizzaIngredient', to='products.ingredient'),
        ),
        migrations.AddConstraint(
            model_name='pizzaingredient',
            constraint=models.UniqueConstraint(fields=('pizza', 'ingredient'), name='unique_pizza_ingredient'),
        ),
    ]
