# Generated by Django 5.2.11 on 2026-05-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pizza',
            index=models.Index(fields=['slug'], name='products_pi_slug_05c49a_idx'),
        ),
        migrations.AddIndex(
            model_name='pizza',
            index=models.Index(fields=['is_featured'], name='products_pi_is_feat_fc691a_idx'),
        ),
        migrations.AddIndex(
            model_name='pizza',
            index=models.Index(fields=['created_at'], name='products_pi_created_727a79_idx'),
        ),
    ]
